### ISSUE TITLE
Cannot add more than 2 MX records with the same PRE value

### ISSUE THREAD

**Issue by Yamakasi** [tools4isp/dnsshop#15]
It's not possible to add more than 2 MX records with the same PRE value.

When you add more, they all need to  be  a different value, so 2 of the same and one different is not possible in this case also.

SO:

10
10
works

10
10
20 
doesn't work

10
20
30
works

**Comment by Petertjuh360** [comment]
Which error do you get?

**Comment by Petertjuh360** [comment]
I am not able to reproduce this problem. I can create a domain with 2x 10 mx records and 1x 20 mx record.

**Comment by Petertjuh360** [comment]
Any update on this?

**Comment by nlmark** [comment]
Please use different priority's. Then it should work.
