### ISSUE TITLE
Replace md5 with sha512 and salt it

### ISSUE THREAD

**Issue by nlmark** [tools4isp/dnsshop#5]

**Comment by Petertjuh360** [comment]
How will the upgrade path go? Will users need to reset their password or should we create an one time use script to decrypt and re-encrypt the passwords?

**Comment by nlmark** [comment]
Upgrade path should be:
1. Resetting passwords OR
2. Update when someone logs in using the old method and replace the password (as at that moment there is an unencripted version available)

For the new version we require resetting passwords.
